// Base UI primitives — thin, typed wrappers over the shared BEM blocks in
// styles.css. Prefer these over hand-written `className` strings; see the
// living gallery at /dev/ui for every variant.
export { default as Avatar } from "@/ui/Avatar"
export { default as Badge, type BadgeState } from "@/ui/Badge"
export { default as Button, type ButtonSize, type ButtonVariant } from "@/ui/Button"
export { default as Card } from "@/ui/Card"
export { default as Checkbox } from "@/ui/Checkbox"
export { default as CodeSnippet } from "@/ui/CodeSnippet"
export { default as Comment } from "@/ui/Comment"
export { default as ConfirmDialog } from "@/ui/ConfirmDialog"
export { default as Dialog } from "@/ui/Dialog"
export { default as EmptyState } from "@/ui/EmptyState"
export { default as ErrorMessage } from "@/ui/ErrorMessage"
export { default as Field } from "@/ui/Field"
export { FilterBar, FilterRow } from "@/ui/FilterBar"
export { default as FilterChip } from "@/ui/FilterChip"
export { type FieldSlot, default as FormField } from "@/ui/FormField"
export { default as Inline } from "@/ui/Inline"
export { default as Input } from "@/ui/Input"
export { default as ListRow } from "@/ui/ListRow"
export { default as Menu, type MenuItem } from "@/ui/Menu"
export { default as PageHeader } from "@/ui/PageHeader"
export { default as Pagination } from "@/ui/Pagination"
export { default as Radio } from "@/ui/Radio"
export { default as RelativeTime } from "@/ui/RelativeTime"
export {
  default as SegmentedControl,
  type SegmentedOption,
} from "@/ui/SegmentedControl"
export { default as Select } from "@/ui/Select"
export { default as Sidebar } from "@/ui/Sidebar"
export { default as SidebarSection } from "@/ui/SidebarSection"
export { default as Skeleton } from "@/ui/Skeleton"
export { default as SkeletonList } from "@/ui/SkeletonList"
export { default as SkeletonTable } from "@/ui/SkeletonTable"
export { default as SkeletonText } from "@/ui/SkeletonText"
export { default as Spinner } from "@/ui/Spinner"
export { default as Stack, type SpaceStep } from "@/ui/Stack"
export { default as StatusIcon, type StatusGlyph } from "@/ui/StatusIcon"
export { default as StatusPill } from "@/ui/StatusPill"
export { default as Switch } from "@/ui/Switch"
export { default as Table } from "@/ui/Table"
export { Tab, Tabs } from "@/ui/Tabs"
export { default as Textarea } from "@/ui/Textarea"
export { ToastProvider, useToast } from "@/ui/Toast"
export { default as Toolbar } from "@/ui/Toolbar"
export { default as Tooltip } from "@/ui/Tooltip"
